name: Postman API Tests

on:
  push:
    branches:
      - Postman-Integrations
  pull_request:
    branches:
      - Postman-Integrations

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: |
          newman run collections/my-collection.json \
            --environment environments/my-environment.json \
            --reporters cli,html \
            --reporter-html-export results/report.html

      - name: Upload test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: postman-test-report
          path: results/