name: Run Postman Tests

on: 
  push:
    branches: 
      - Postman-Integration
  pull_request:
    branches:
      - Postman-Integration

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Tests
      run: |
        newman run .github/workflows/System Tests.postman_collection.json \
        --environment .github/workflows/System Tests.postman_environment.json \
        --reporters cli,junit \
        --reporter-junit-export results.xml
